routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'MemberController@index')->name('member');


Route::group(['middleware' => 'App\Http\Middleware\AdminMiddleware'], function()
{

	Route::match(['get', 'post'], '/admin', 'HomeController@admin');
	Route::resource('room', 'RoomsController');

});


Route::get('/member', 'MemberController@index')->name('member');
Route::get('/rooms/{id}', 'MemberController@show')->name('rooms.show');
Route::post('/booking', 'MemberController@insert')->name('booking');
Route::get('/options/{id}', 'MemberController@getOptions')->name('booking.options');
Route::get('/member/rooms/{id}', 'MemberController@bookingRooms')->name('booking.rooms');
Route::post('/extension', 'MemberController@extension')->name('booking.extension');
Route::post('/bookingdestroy/{id}', 'MemberController@bookingDestroy')->name('booking.destroy');

resources/views/admin/create.blade.php
@extends('layouts.app')

@section('content')
{{ Breadcrumbs::render('create') }}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header" style="background-color: #2C3E50;color:white">BookingRooom</div>

                <div class="card-body">
                    @if (session('message'))
                        <div class="alert alert-success" role="alert">
                            {{ session('message') }}
                        </div>
                    @endif

                    <form method="post" action="{{route('room.store')}}" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group">
                            <label for="title">Название Комнаты</label>
                            <input type="text" class="form-control" id="title" name="title" aria-describedby="emailHelp" placeholder="Название Комнаты" required>  
                            <input class="mt-3" type="file" id="image" name="image">                 
                        </div>
                      <input type="submit" class="btn btn-primary" value="Добавить комнату">
                        
                    </form>
                    @error('title')
                        <div class="alert alert-warning mt-3" role="alert">
                            Такая комната уже существует!!
                        </div>
                    @enderror
                    @error('image')
                        <div class="alert alert-warning mt-3" role="alert">
                            Ошибка в поле картинка!!
                        </div>
                    @enderror
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/edit.blade.php
@extends('layouts.app')

@section('content')
{{ Breadcrumbs::render('edit') }}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header"  style="background-color: #2C3E50;color:white">BookingRooom</div>

                <div class="card-body">
                    @if (session('message'))
                        <div class="alert alert-success" role="alert">
                            {{ session('message') }}
                        </div>
                    @endif

                    <form method="post" action="{{route('room.update', $data->id)}}"  enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                            <label for="title">Название Комнаты</label>
                            <input type="text" class="form-control" id="title" name="title" aria-describedby="emailHelp" placeholder="Название Комнаты" required value="{{$data->title}}">  
                            <input class="mt-3" type="file" id="image" name="image">                  
                        </div>
                      <input type="submit" class="btn btn-primary" value="Изменить комнату">
                        
                    </form>
                    @error('title')
                        <div class="alert alert-warning mt-3" role="alert">
                            Такая комната уже существует!!
                        </div>
                    @enderror
                    @error('image')
                        <div class="alert alert-warning mt-3" role="alert">
                            Ошибка в поле картинка!!
                        </div>
                    @enderror
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/home.blade.php
@extends('layouts.app')

@section('content')
  {{ Breadcrumbs::render('admin') }}
<div class="container-fluid">
@if (session('message'))
    <div class="alert alert-success" role="alert">
        {{ session('message') }}
    </div>
@endif
    <table class="table" id="datatable">
  <thead class="thead" style="background-color: #2C3E50;color:white">
    <tr>
      <th scope="col">N:</th>
      <th scope="col">Название</th>
      <th scope="col">Удалить</th>
      <th scope="col">Изменить</th>
    </tr>
  </thead>
  <tbody>
    @foreach($data as $row)
    <tr>
      <th scope="row">{{$row->id}}</th>
      <td>{{$row->title}}</td>
      <td>
        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#modalDelete{{$row->id}}">
          Удалить
        </button>
      </td>
      <td><a class="btn btn-warning" href="{{route('room.edit', $row->id)}}">Изменить</a></td>
    </tr>
    <!-- Modal -->
    <div class="modal fade" id="modalDelete{{$row->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Безвозвратное удаление комнаты!!</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            Подтвердите действие
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-success" data-dismiss="modal">Отменить</button>
            <form method="post" action="{{route('room.destroy', $row->id)}}">
              @csrf
              @method('DELETE')
              <button class="btn btn-danger">Продолжить</button>
            </form>
          </div>
        </div>
      </div>
    </div>
    @endforeach
  </tbody>
</table>
</div>
@endsection
<!-- Button trigger modal -->

resources/views/admin/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">BookingRooom</div>
                
                <div class="card-body">
                    @if (session('message'))
                        <div class="alert alert-success" role="alert">
                            {{ session('message') }}
                        </div>
                    @endif

                    @foreach($data as $row)
                       <div class="form-group">
                            <a  class="btn btn-primary mt-4" href="{{route('room.show', $row->id)}}">{{$row->title}}</a>                  
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">BookingRooom</div>

                <div class="card-body">
                    @if (session('message'))
                        <div class="alert alert-success" role="alert">
                            {{ session('message') }}
                        </div>
                    @endif
                       <div class="form-group">
                            <h3>{{$data->title}}</h3>
                            <a class="btn btn-warning" href="{{route('room.edit', $data->id)}}">Изменить</a>
                            <form method="post" action="{{route('room.destroy', $data->id)}}">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger mt-4">Удалить</button>
                            </form>                  
                        </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection